# replace \' => \' &quot #039

question_category = {
    1: 'General Knowledge',
    2: "Entertainment: Books",
    3: "Entertainment: Film",
    4: "Entertainment: Music",
    5: "Entertainment: Musicals & Theatres",
    6: "Entertainment: Television",
    7: "Entertainment: Video Games",
    8: "Entertainment: Board Games",
    9: "Science & Nature",
    10: "Science: Computers",
    11: "Science: Mathematics",
    12: "Mythology",
    13: "Sports",
    14: "Geography",
    15: "History",
    16: "Politics",
    17: "Art",
    18: "Celebrities",
    19: "Animals",
    20: "Vehicles",
    21: "Entertainment: Comics",
    22: "Science: Gadgets",
    23: "Entertainment: Japanese Anime & Manga",
    24: "Entertainment: Cartoon & Animations",

}
question_data_science = {"response_code": 0,
                         "results": [{"category": "Science: Computers",
                                      "type": "multiple",
                                      "difficulty": "easy",
                                      "question": "The programming language \'Swift\' was created to replace what other programming language?",
                                      "correct_answer": "Objective-C",
                                      "incorrect_answers": ["C#", "Ruby", "C++"]},
                                     {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
                                      "question": "HTML is what type of language?", "correct_answer": "Markup Language",
                                      "incorrect_answers": ["Macro Language", "Programming Language",
                                                            "Scripting Language"]},
                                     {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
                                      "question": "What amount of bits commonly equals one byte?",
                                      "correct_answer": "8",
                                      "incorrect_answers": ["1", "2", "64"]},
                                     {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
                                      "question": "In the programming language Java, which of these keywords would you put on a variable to make sure it doesn\'t get modified?",
                                      "correct_answer": "Final", "incorrect_answers": ["Static", "Private", "Public"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                      "question": "The programming language \"Python\" is based off a modified version of \"JavaScript\".",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                      "question": "The logo for Snapchat is a Bell.", "correct_answer": "False",
                                      "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
                                      "question": "If you were to code software in this language you\'d only be able to type 0\'s and 1\'s.",
                                      "correct_answer": "Binary", "incorrect_answers": ["JavaScript", "C++", "Python"]},
                                     {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
                                      "question": "In web design, what does CSS stand for?",
                                      "correct_answer": "Cascading Style Sheet",
                                      "incorrect_answers": ["Counter Strike: Source", "Corrective Style Sheet",
                                                            "Computer Style Sheet"]},
                                     {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
                                      "question": "What is the code name for the mobile operating system Android 7.0?",
                                      "correct_answer": "Nougat",
                                      "incorrect_answers": ["Ice Cream Sandwich", "Jelly Bean", "Marshmallow"]},
                                     {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
                                      "question": "What is the domain name for the country Tuvalu?",
                                      "correct_answer": ".tv",
                                      "incorrect_answers": [".tu", ".tt", ".tl"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                      "question": "Ada Lovelace is often considered the first computer programmer.",
                                      "correct_answer": "True",
                                      "incorrect_answers": ["False"]},
                                     {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
                                      "question": "On Twitter, what was the original character limit for a Tweet?",
                                      "correct_answer": "140", "incorrect_answers": ["120", "160", "100"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                      "question": "\"HTML\" stands for Hypertext Markup Language.",
                                      "correct_answer": "True",
                                      "incorrect_answers": ["False"]},
                                     {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
                                      "question": "In \"Hexadecimal\", what color would be displayed from the color code? \"#00FF00\"?",
                                      "correct_answer": "Green", "incorrect_answers": ["Red", "Blue", "Yellow"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                      "question": "In most programming languages, the operator ++ is equivalent to the statement \"+= 1\".",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                      "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
                                      "question": "Which programming language shares its name with an island in Indonesia?",
                                      "correct_answer": "Java",
                                      "incorrect_answers": ["Python", "C", "Jakarta"]},
                                     {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
                                      "question": "In computing, what does MIDI stand for?",
                                      "correct_answer": "Musical Instrument Digital Interface",
                                      "incorrect_answers": ["Musical Interface of Digital Instruments",
                                                            "Modular Interface of Digital Instruments",
                                                            "Musical Instrument Data Interface"]},
                                     {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
                                      "question": "What language does Node.js use?", "correct_answer": "JavaScript",
                                      "incorrect_answers": ["Java", "Java Source", "Joomla Source Code"]},
                                     {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
                                      "question": "What does the computer software acronym JVM stand for?",
                                      "correct_answer": "Java Virtual Machine",
                                      "incorrect_answers": ["Java Vendor Machine", "Java Visual Machine",
                                                            "Just Virtual Machine"]}]
                         }
question_data_animal = {"response_code": 0, "results": [
    {"category": "Animals", "type": "multiple", "difficulty": "easy", "question": "What is the fastest  land animal?",
     "correct_answer": "Cheetah", "incorrect_answers": ["Lion", "Thomson\'s Gazelle", "Pronghorn Antelope"]},
    {"category": "Animals", "type": "multiple", "difficulty": "easy",
     "question": "What is the scientific name for modern day humans?", "correct_answer": "Homo Sapiens",
     "incorrect_answers": ["Homo Ergaster", "Homo Erectus", "Homo Neanderthalensis"]},
    {"category": "Animals", "type": "multiple", "difficulty": "easy",
     "question": "The K\u0101k\u0101p\u014d is a large, flightless, nocturnal parrot native to which country?",
     "correct_answer": "New Zealand", "incorrect_answers": ["South Africa", "Australia", "Madagascar"]},
    {"category": "Animals", "type": "multiple", "difficulty": "easy",
     "question": "Hippocampus is the Latin name for which marine creature?", "correct_answer": "Seahorse",
     "incorrect_answers": ["Dolphin", "Whale", "Octopus"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "Kangaroos keep food in their pouches next to their children.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "Animals", "type": "boolean", "difficulty": "easy",
                                      "question": "A bear does NOT defecate during hibernation. ",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "multiple", "difficulty": "easy", "question": "How many legs do butterflies have?",
     "correct_answer": "6", "incorrect_answers": ["2", "4", "0"]},
    {"category": "Animals", "type": "multiple", "difficulty": "easy", "question": "What do you call a baby bat?",
     "correct_answer": "Pup", "incorrect_answers": ["Cub", "Chick", "Kid"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "In 2016, the IUCN reclassified the status of Giant Pandas from endangered to vulnerable.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy", "question": "Rabbits are rodents.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "A flock of crows is known as a homicide.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Animals", "type": "multiple", "difficulty": "easy",
     "question": "What is Grumpy Cat\'s real name?", "correct_answer": "Tardar Sauce",
     "incorrect_answers": ["Sauce", "Minnie", "Broccoli"]},
    {"category": "Animals", "type": "multiple", "difficulty": "easy",
     "question": "Which class of animals are newts members of?", "correct_answer": "Amphibian",
     "incorrect_answers": ["Fish", "Reptiles", "Mammals"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "A caterpillar has more muscles than humans do.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy", "question": "Cats have whiskers under their legs.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "multiple", "difficulty": "easy",
     "question": "What is the collective noun for a group of crows?", "correct_answer": "Murder",
     "incorrect_answers": ["Pack", "Gaggle", "Herd"]}, {"category": "Animals", "type": "multiple", "difficulty": "easy",
                                                        "question": "By definition, where does an abyssopelagic animal live?",
                                                        "correct_answer": "At the bottom of the ocean",
                                                        "incorrect_answers": ["In the desert", "On top of a mountain",
                                                                              "Inside a tree"]},
    {"category": "Animals", "type": "multiple", "difficulty": "easy",
     "question": "How many teeth does an adult rabbit have?", "correct_answer": "28",
     "incorrect_answers": ["30", "26", "24"]}, {"category": "Animals", "type": "multiple", "difficulty": "easy",
                                                "question": "What is the name of a rabbit\'s abode?",
                                                "correct_answer": "Burrow",
                                                "incorrect_answers": ["Nest", "Den", "Dray"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "The freshwater amphibian, the Axolotl, can regrow it\'s limbs.", "correct_answer": "True",
     "incorrect_answers": ["False"]}]}

question_data_general = {"response_code": 0, "results": [
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "Area 51 is located in which US state?", "correct_answer": "Nevada",
     "incorrect_answers": ["Arizona", "New Mexico", "Utah"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "Which sign of the zodiac is represented by the Crab?", "correct_answer": "Cancer",
     "incorrect_answers": ["Libra", "Virgo", "Sagittarius"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What is the shape of the toy invented by Hungarian professor Ern\u0151 Rubik?",
     "correct_answer": "Cube", "incorrect_answers": ["Sphere", "Cylinder", "Pyramid"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "How many colors are there in a rainbow?", "correct_answer": "7",
     "incorrect_answers": ["8", "9", "10"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                              "question": "A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.",
                                              "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What is the nickname of the US state of California?", "correct_answer": "Golden State",
     "incorrect_answers": ["Sunshine State", "Bay State", "Treasure State"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What is the Spanish word for \"donkey\"?", "correct_answer": "Burro",
     "incorrect_answers": ["Caballo", "Toro", "Perro"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "The color orange is named after the fruit.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "Pluto is a planet.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "When you cry in space, your tears stick to your face.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
                                       "question": "Which of the following card games revolves around numbers and basic math?",
                                       "correct_answer": "Uno",
                                       "incorrect_answers": ["Go Fish", "Twister", "Munchkin"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What machine element is located in the center of fidget spinners?", "correct_answer": "Bearings",
     "incorrect_answers": ["Axles", "Gears", "Belts"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What is the Zodiac symbol for Gemini?", "correct_answer": "Twins",
     "incorrect_answers": ["Fish", "Scales", "Maiden"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What zodiac sign is represented by a pair of scales?", "correct_answer": "Libra",
     "incorrect_answers": ["Aries", "Capricorn", "Sagittarius"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "The Flag of the European Union has how many stars on it?", "correct_answer": "12",
     "incorrect_answers": ["10", "14", "16"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "How many furlongs are there in a mile?", "correct_answer": "Eight",
     "incorrect_answers": ["Two", "Four", "Six"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Slovakia is a member of European Union-", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "Which of the following blood component forms a plug at the site of injuries?",
     "correct_answer": "Platelets", "incorrect_answers": ["Red blood cells", "White blood cells", "Blood plasma"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What is the famous Papa John&\'s last name?", "correct_answer": "Schnatter",
     "incorrect_answers": ["Chowder", "Williams", "ANDERSON"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What kind of aircraft was developed by Igor Sikorsky in the United States in 1942?",
     "correct_answer": "Helicopter", "incorrect_answers": ["Stealth Blimp", "Jet", "Space Capsule"]}]}

assafsf = {'response_code': 0, 'results': [
    {'category': 'Entertainment: Books', 'type': 'multiple', 'difficulty': 'easy',
     'question': "Who wrote 'Harry Potter'?", 'correct_answer': 'J.K. Rowling',
     'incorrect_answers': ['J.R.R. Tolkien', 'Terry Pratchett', 'Daniel Radcliffe']},
    {'category': 'Entertainment: Books', 'type': 'multiple', 'difficulty': 'easy',
     'question': 'George Orwell wrote this book, which is often considered a statement on government oversight.',
     'correct_answer': '1984',
     'incorrect_answers': ['The Old Man and the Sea', 'Catcher and the Rye', 'To Kill a Mockingbird']},
    {'category': 'Entertainment: Books', 'type': 'multiple', 'difficulty': 'easy',
     'question': "Who wrote the novel 'Fear And Loathing In Las Vegas'?", 'correct_answer': 'Hunter S. Thompson',
     'incorrect_answers': ['F. Scott Fitzgerald', 'Henry Miller', 'William S. Burroughs']},
    {'category': 'Entertainment: Books', 'type': 'multiple', 'difficulty': 'easy',
     'question': "'Green Eggs And Ham' is a book by which author?", 'correct_answer': 'Dr. Seuss',
     'incorrect_answers': ['Beatrix Potter', 'Roald Dahl', 'A.A. Milne']},
    {'category': 'Entertainment: Books', 'type': 'multiple', 'difficulty': 'easy',
     'question': "Which famous spy novelist wrote the childrens' story 'Chitty-Chitty-Bang-Bang'?",
     'correct_answer': 'Ian Fleming', 'incorrect_answers': ['Joseph Conrad', 'John Buchan', 'Graham Greene']},
    {'category': 'Entertainment: Books', 'type': 'boolean', 'difficulty': 'easy',
     'question': "The 'Berenstein Bears' is the correct spelling of the educational children's book series' name.",
     'correct_answer': 'False', 'incorrect_answers': ['True']},
    {'category': 'Entertainment: Books', 'type': 'boolean', 'difficulty': 'easy',
     'question': 'The book 1984 was published in 1949.', 'correct_answer': 'True', 'incorrect_answers': ['False']},
    {'category': 'Entertainment: Books', 'type': 'multiple', 'difficulty': 'easy',
     'question': 'How many Harry Potter books are there?', 'correct_answer': '7', 'incorrect_answers': ['8', '5', '6']},
    {'category': 'Entertainment: Books', 'type': 'multiple', 'difficulty': 'easy',
     'question': "Who wrote the young adult novel 'The Fault in Our Stars'?", 'correct_answer': 'John Green',
     'incorrect_answers': ['Stephenie Meyer', 'Suzanne Collins', 'Stephen Chbosky']},
    {'category': 'Entertainment: Books', 'type': 'multiple', 'difficulty': 'easy',
     'question': "Who was the author of the 1954 novel, 'Lord of the Flies'?", 'correct_answer': 'William Golding',
     'incorrect_answers': ['Stephen King', 'F. Scott Fitzgerald', 'Hunter Fox']},
    {'category': 'Entertainment: Books', 'type': 'boolean', 'difficulty': 'easy',
     'question': "'Elementary, my dear Watson' is a phrase that is never truly said within the Conan Doyle books of Sherlock Holmes.",
     'correct_answer': 'True', 'incorrect_answers': ['False']},
    {'category': 'Entertainment: Books', 'type': 'multiple', 'difficulty': 'easy',
     'question': "What is the name of the three headed dog in Harry Potter and the Sorcerer's Stone?",
     'correct_answer': 'Fluffy', 'incorrect_answers': ['Spike', 'Poofy', 'Spot']},
    {'category': 'Entertainment: Books', 'type': 'multiple', 'difficulty': 'easy',
     'question': "What is the name of the protagonist of J.D. Salinger's novel Catcher in the Rye?",
     'correct_answer': 'Holden Caulfield', 'incorrect_answers': ['Fletcher Christian', 'Jay Gatsby', 'Randall Flagg']},
    {'category': 'Entertainment: Books', 'type': 'multiple', 'difficulty': 'easy',
     'question': 'What is the title of the first Sherlock Holmes book by Arthur Conan Doyle?',
     'correct_answer': 'A Study in Scarlet',
     'incorrect_answers': ['The Sign of the Four', 'A Case of Identity', 'The Doings of Raffles Haw']},
    {'category': 'Entertainment: Books', 'type': 'multiple', 'difficulty': 'easy',
     'question': "What's the second book in George R. R. Martin's 'A Song of Ice and Fire' series?",
     'correct_answer': 'A Clash of Kings',
     'incorrect_answers': ['A Dance with Dragons', 'A Storm of Swords', 'A Feast for Crows']},
    {'category': 'Entertainment: Books', 'type': 'boolean', 'difficulty': 'easy',
     'question': "'Green Eggs and Ham' consists of only 50 different words.", 'correct_answer': 'True',
     'incorrect_answers': ['False']}, {'category': 'Entertainment: Books', 'type': 'multiple', 'difficulty': 'easy',
                                       'question': 'Which is NOT a book in the Harry Potter Series?',
                                       'correct_answer': 'The House Elf',
                                       'incorrect_answers': ['The Chamber of Secrets', 'The Prisoner of Azkaban',
                                                             'The Deathly Hallows']},
    {'category': 'Entertainment: Books', 'type': 'boolean', 'difficulty': 'easy',
     'question': 'The Harry Potter series of books, combined, are over 1,000,000 words in length.',
     'correct_answer': 'True', 'incorrect_answers': ['False']},
    {'category': 'Entertainment: Books', 'type': 'multiple', 'difficulty': 'easy',
     'question': "Who wrote 'A Tale of Two Cities'?", 'correct_answer': 'Charles Dickens',
     'incorrect_answers': ['Charles Darwin', 'Mark Twain', 'Roald Dahl']},
    {'category': 'Entertainment: Books', 'type': 'boolean', 'difficulty': 'easy',
     'question': "Shub-Niggurath is a creature that was created by \tJ. R. R. Tolkien in his novel 'The Lord of The Rings'.",
     'correct_answer': 'False', 'incorrect_answers': ['True']}]}
